//go:build amd64

package popcount

import "golang.org/x/sys/cpu"

// countPOPCNT is the 4-way-unrolled hardware POPCNTQ kernel; countAVX2 is the
// AVX2 VPSHUFB/Harley-Seal kernel. Each totals the set bits of whole 32-byte
// (POPCNT) or 512-byte (AVX2) blocks of data and returns that partial popcount
// plus the number of bytes consumed. Generated by go-asmgen (count_gen.go), in
// count_amd64.s.
func countPOPCNT(data []byte) (sum, done int)
func countAVX2(data []byte) (sum, done int)

var (
	hasPOPCNT = cpu.X86.HasPOPCNT
	hasAVX2   = cpu.X86.HasAVX2
)

// Per-kernel minimum input sizes. POPCNT needs one 32-byte block; AVX2 needs one
// 512-byte Harley-Seal block. Below these the scalar OnesCount64 loop wins
// because the kernel setup plus scalar tail does not amortise.
const (
	popcntThreshold = 32
	avx2Threshold   = 512
)

// count totals the set bits of data. On a CPU with hardware POPCNT it runs the
// 4-way-unrolled POPCNTQ kernel (the fastest path — POPCNT saturates memory
// bandwidth); on a POPCNT-less but AVX2 CPU it runs the Harley-Seal kernel;
// otherwise, and for inputs below the kernel threshold, it is the scalar
// OnesCount64 loop. Whole blocks go through the kernel and the remainder through
// the scalar tail, so the result equals countScalarRef(data) exactly.
func count(data []byte) int {
	if hasPOPCNT && len(data) >= popcntThreshold {
		sum, done := countPOPCNT(data)
		return sum + countScalarRef(data[done:])
	}
	if hasAVX2 && len(data) >= avx2Threshold {
		sum, done := countAVX2(data)
		return sum + countScalarRef(data[done:])
	}
	return countScalarRef(data)
}
