//go:build s390x

package popcount

// countVX totals the set bits of whole 16-byte blocks of data with the vector-
// facility VPOPCT per-byte popcount and a VSUMB/VSUMQF horizontal sum, returning
// that partial popcount and the number of bytes consumed (a multiple of 16).
// Generated by go-asmgen (count_s390x_gen.go), in count_s390x.s. The vector
// facility (z13) is the s390x baseline, so there is no runtime feature check.
func countVX(data []byte) (sum, done int)

// vxThreshold is the smallest input for which the vector kernel is used.
const vxThreshold = 16

// count totals the set bits of data: the vector kernel over whole 16-byte
// blocks, then the scalar OnesCount64 loop on the remainder. The result equals
// countScalarRef(data) exactly.
func count(data []byte) int {
	if len(data) >= vxThreshold {
		sum, done := countVX(data)
		return sum + countScalarRef(data[done:])
	}
	return countScalarRef(data)
}
