// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·countLSX(SB), NOSPLIT, $0-40
	MOVV data_base+0(FP), R4
	MOVV data_len+8(FP), R5
	MOVV $0, R6
	MOVV $0, R7
loop:
	ADDV $16, R7, R8
	BLT R5, R8, done
	ADDV R4, R7, R9
	VMOVQ (R9), V0
	VPCNTV V0, V0
	VMOVQ V0.V[0], R10
	VMOVQ V0.V[1], R11
	ADDV R10, R6, R6
	ADDV R11, R6, R6
	ADDV $16, R7, R7
	JMP loop
done:
	MOVV R6, sum+24(FP)
	MOVV R7, done+32(FP)
	RET

