//go:build loong64

package popcount

// countLSX totals the set bits of whole 16-byte blocks of data with the LSX
// VPCNTV per-64-bit-element popcount, returning that partial popcount and the
// number of bytes consumed (a multiple of 16). Generated by go-asmgen
// (count_loong64_gen.go), in count_loong64.s.
func countLSX(data []byte) (sum, done int)

// lsxThreshold is the smallest input for which the LSX kernel is used.
const lsxThreshold = 16

// count totals the set bits of data: the LSX kernel over whole 16-byte blocks,
// then the scalar OnesCount64 loop on the remainder. The result equals
// countScalarRef(data) exactly.
func count(data []byte) int {
	if len(data) >= lsxThreshold {
		sum, done := countLSX(data)
		return sum + countScalarRef(data[done:])
	}
	return countScalarRef(data)
}
