//go:build ppc64le

package popcount

import "golang.org/x/sys/cpu"

// countVSX totals the set bits of whole 16-byte blocks of data with the VSX
// VPOPCNTD per-64-bit-doubleword popcount, returning that partial popcount and
// the number of bytes consumed (a multiple of 16). Generated by go-asmgen
// (count_ppc64le_gen.go), in count_ppc64le.s. The kernel extracts the
// doubleword sums with MFVSRLD, an ISA-3.0 (POWER9) instruction that raises
// SIGILL on POWER8, so it runs only when hasVSX reports POWER9+; POWER8 folds
// every byte through the scalar countScalarRef loop.
func countVSX(data []byte) (sum, done int)

// vsxThreshold is the smallest input for which the VSX kernel is used.
const vsxThreshold = 16

// hasVSX is the dispatch flag. The generated kernel emits the ISA-3.0 (POWER9)
// MFVSRLD instruction, which is illegal on POWER8, so the kernel is gated on
// POWER9 detection; on POWER8 count falls back entirely to the scalar
// countScalarRef loop. It is a var (not a const) so the dispatch test can also
// drive the no-SIMD fallback on a POWER9+ host.
var hasVSX = cpu.PPC64.IsPOWER9

// count totals the set bits of data: on POWER9+ the VSX kernel over whole
// 16-byte blocks plus the scalar OnesCount64 loop on the remainder; on POWER8
// (hasVSX false) the scalar countScalarRef loop over the whole slice. The
// result equals countScalarRef(data) exactly.
func count(data []byte) int {
	if hasVSX && len(data) >= vsxThreshold {
		sum, done := countVSX(data)
		return sum + countScalarRef(data[done:])
	}
	return countScalarRef(data)
}
