//go:build arm64

package popcount

// countNEON totals the set bits of whole 64-byte blocks of data with NEON VCNT,
// returning that partial popcount and the number of bytes consumed (a multiple
// of 64). Generated by go-asmgen (count_arm64_gen.go), in count_arm64.s.
func countNEON(data []byte) (sum, done int)

// neonThreshold is the smallest input for which the NEON kernel is used; below
// it the scalar OnesCount64 loop is at least as fast and avoids the call.
const neonThreshold = 64

// count totals the set bits of data: the NEON kernel over whole 64-byte blocks,
// then the scalar OnesCount64 loop on the remainder. The result equals
// countScalarRef(data) exactly.
func count(data []byte) int {
	if len(data) >= neonThreshold {
		sum, done := countNEON(data)
		return sum + countScalarRef(data[done:])
	}
	return countScalarRef(data)
}
