// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·countNEON(SB), NOSPLIT, $0-40
	MOVD data_base+0(FP), R0
	MOVD data_len+8(FP), R1
	MOVD $0, R2
	MOVD $0, R3
loop:
	ADD $64, R3, R4
	CMP R1, R4
	BGT done
	ADD R0, R3, R5
	VLD1.P 64(R5), [V0.B16, V1.B16, V2.B16, V3.B16]
	VCNT V0.B16, V0.B16
	VCNT V1.B16, V1.B16
	VCNT V2.B16, V2.B16
	VCNT V3.B16, V3.B16
	VADD V1.B16, V0.B16, V0.B16
	VADD V3.B16, V2.B16, V2.B16
	VADD V2.B16, V0.B16, V0.B16
	VUADDLV V0.B16, V0
	VMOV V0.D[0], R6
	ADD R6, R2, R2
	ADD $64, R3, R3
	JMP loop
done:
	MOVD R2, sum+24(FP)
	MOVD R3, done+32(FP)
	RET

