//go:build ppc64le

package popcount

// countVSX totals the set bits of whole 16-byte blocks of data with the VSX
// VPOPCNTD per-64-bit-doubleword popcount, returning that partial popcount and
// the number of bytes consumed (a multiple of 16). Generated by go-asmgen
// (count_ppc64le_gen.go), in count_ppc64le.s. VSX (POWER8) is the ppc64le
// baseline, so there is no runtime feature check.
func countVSX(data []byte) (sum, done int)

// vsxThreshold is the smallest input for which the VSX kernel is used.
const vsxThreshold = 16

// count totals the set bits of data: the VSX kernel over whole 16-byte blocks,
// then the scalar OnesCount64 loop on the remainder. The result equals
// countScalarRef(data) exactly.
func count(data []byte) int {
	if len(data) >= vsxThreshold {
		sum, done := countVSX(data)
		return sum + countScalarRef(data[done:])
	}
	return countScalarRef(data)
}
