// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·countVX(SB), NOSPLIT, $0-40
	MOVD data_base+0(FP), R1
	MOVD data_len+8(FP), R2
	MOVD $0, R3
	MOVD $0, R4
	VZERO V2
loop:
	ADD $16, R4, R5
	CMPBGT R5, R2, done
	ADD R1, R4, R6
	VL (R6), V0
	VPOPCT V0, V1
	VSUMB V1, V2, V1
	VSUMQF V1, V2, V1
	VLGVG $1, V1, R7
	ADD R7, R3, R3
	ADD $16, R4, R4
	BR loop
done:
	MOVD R3, sum+24(FP)
	MOVD R4, done+32(FP)
	RET

