// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·countVSX(SB), NOSPLIT, $0-40
	MOVD data_base+0(FP), R3
	MOVD data_len+8(FP), R4
	MOVD $0, R5
	MOVD $0, R6
loop:
	ADD $16, R6, R7
	CMP R7, R4
	BGT done
	ADD R3, R6, R8
	LXVD2X (R8)(R0), VS32
	VPOPCNTD V0, V0
	MFVSRD VS32, R9
	MFVSRLD VS32, R10
	ADD R9, R5, R5
	ADD R10, R5, R5
	ADD $16, R6, R6
	BR loop
done:
	MOVD R5, sum+24(FP)
	MOVD R6, done+32(FP)
	RET

