// Package popcount counts the total number of set bits (the population count,
// a.k.a. Hamming weight) of a byte slice in pure Go (CGO_ENABLED=0, stable Go,
// no GOEXPERIMENT). The hot loop is a SIMD kernel generated by go-asmgen on
// amd64 (AVX2 VPSHUFB nibble-lookup with a Harley-Seal CSA tree, scalar POPCNT
// fallback), arm64 (NEON VCNT), loong64 (LSX VPCNTV), ppc64le (VSX VPOPCNTD)
// and s390x (vector-facility VPOPCT + VSUMB/VSUMQF); every other architecture
// (including riscv64, whose RVV lacks a per-element byte popcount) uses a
// portable math/bits.OnesCount64 word loop.
//
// The honest framing: a scalar OnesCount64 loop already runs at roughly eight
// bytes per cycle, so for large, out-of-cache buffers Count is
// memory-bandwidth-bound and SIMD cannot beat scalar — it ties. The SIMD win is
// real for in-cache / medium buffers, where the problem is compute-bound. See
// the package README for the measured size-dependent throughput.
package popcount

import "math/bits"

// Count returns the total number of set bits across all bytes of data: the sum
// of bits.OnesCount8(b) over every byte b in data. It reads data only and is
// safe for concurrent use on distinct (or shared, read-only) slices.
func Count(data []byte) int {
	return count(data)
}

// countScalarRef is the reference population count: a math/bits.OnesCount64 loop
// over 64-bit words with an OnesCount8 byte tail. It is the scalar baseline the
// SIMD kernels must beat in-cache and tie out-of-cache, and the oracle the tests
// and fuzzer compare against. It is also the generic (non-SIMD) implementation.
func countScalarRef(data []byte) int {
	total := 0
	i := 0
	n := len(data)
	// Eight bytes per word. The loop is fully pipelined; POPCNT is 1/cycle.
	for ; i+8 <= n; i += 8 {
		w := uint64(data[i]) | uint64(data[i+1])<<8 | uint64(data[i+2])<<16 |
			uint64(data[i+3])<<24 | uint64(data[i+4])<<32 | uint64(data[i+5])<<40 |
			uint64(data[i+6])<<48 | uint64(data[i+7])<<56
		total += bits.OnesCount64(w)
	}
	for ; i < n; i++ {
		total += bits.OnesCount8(data[i])
	}
	return total
}
